"""create bikes table

Revision ID: 8d4d06352601
Revises: 
Create Date: 2026-03-24 16:58:38.956137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4d06352601'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('Cross', 'Mountain', 'Street', name='biketype'), nullable=False),
    sa.Column('colour', sa.String(length=50), nullable=False),
    sa.Column('state', sa.Enum('Rented', 'Free', name='bikestate'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bikes')
    # ### end Alembic commands ###
