apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-map
  template:
    metadata:
      labels:
        app: service-map
    spec:
      containers:
        - name: service-map
          image: mvasquezb99/service-map:v8
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: secret-firebase
            - secretRef:
                name: secret-map
