apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-bikes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-bikes
  template:
    metadata:
      labels:
        app: service-bikes
    spec:
      containers:
        - name: service-bikes
          image: mvasquezb99/service-bikes:v9
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: secret-firebase
            - secretRef:
                name: secret-bikes
