apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-rentals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-rentals
  template:
    metadata:
      labels:
        app: service-rentals
    spec:
      containers:
        - name: service-rentals
          image: mvasquezb99/service-rentals:v5
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: secret-firebase
            - secretRef:
                name: secret-rentals
