apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-events
  template:
    metadata:
      labels:
        app: service-events
    spec:
      containers:
        - name: service-events
          image: mvasquezb99/service-events:v2
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: secret-firebase
            - secretRef:
                name: secret-events
